framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
        transports:
            amqp_email_notifications: '%env(MESSENGER_TRANSPORT_DSN)%email-notifications'
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%messenger'
            sync: 'sync://'
        routing:
            'App\Shared\Domain\Bus\Command\Command': amqp